apiVersion: apps/v1
kind: Deployment
metadata:
  name: produk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: produk
  template:
    metadata:
      labels:
        app: produk
    spec:
      containers:
        - name: produk
          image: rogeriocheguevara/produk-service:latest
          ports:
            - containerPort: 3002

---
apiVersion: v1
kind: Service
metadata:
  name: produk-service
spec:
  selector:
    app: produk
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 3002

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pembayaran
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pembayaran
  template:
    metadata:
      labels:
        app: pembayaran
    spec:
      containers:
        - name: pembayaran
          image: rogeriocheguevara/pembayaran-service:latest
          ports:
            - containerPort: 3003

---
apiVersion: v1
kind: Service
metadata:
  name: pembayaran-service
spec:
  selector:
    app: pembayaran
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 3003

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pengiriman
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pengiriman
  template:
    metadata:
      labels:
        app: pengiriman
    spec:
      containers:
        - name: pengiriman
          image: rogeriocheguevara/pengiriman-service:latest
          ports:
            - containerPort: 3004

---
apiVersion: v1
kind: Service
metadata:
  name: pengiriman-service
spec:
  selector:
    app: pengiriman
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 3004
